{{- if .Values.hubDb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "neurondb-hub.fullname" . }}-hub-db-pvc
  labels:
    {{- include "neurondb-hub.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hubDb.persistence.size }}
  {{- if .Values.hubDb.persistence.storageClass }}
  storageClassName: {{ .Values.hubDb.persistence.storageClass }}
  {{- end }}
{{- end }}
