apiVersion: v2
name: neurondb
description: A Helm chart for NeuronDB PostgreSQL AI ecosystem
type: application
version: 4.0.0-devel
appVersion: "4.0.0-devel"
keywords:
  - postgresql
  - vector-database
  - ai
  - embeddings
maintainers:
  - name: NeuronDB Team
    email: support@neurondb.ai



