-- ============================================================================
-- NeurondB Extension Cleanup Script (100_)
-- Drops all NeurondB objects to allow CASCADE drop of extension
-- 
-- This script drops all objects created by the NeurondB extension in the
-- correct order to avoid dependency issues. After running this script,
-- you can safely execute: DROP EXTENSION neurondb CASCADE;
-- 
-- Copyright (c) 2024-2026, neurondb, Inc. <admin@neurondb.com>
-- ============================================================================

\echo '============================================================================'
\echo 'NeurondB Extension Cleanup (100_)'
\echo 'Dropping all NeurondB objects...'
\echo '============================================================================'

-- First, try to drop the extension directly (this will CASCADE to all owned objects)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'neurondb') THEN
        RAISE NOTICE 'Extension neurondb is installed. Dropping extension with CASCADE...';
        EXECUTE 'DROP EXTENSION neurondb CASCADE';
        RAISE NOTICE 'Extension neurondb dropped successfully.';
        RETURN;
    END IF;
    RAISE NOTICE 'Extension neurondb is not installed. Cleaning up remaining objects...';
END $$;

DROP FUNCTION IF EXISTS neurondb.build_knn_graph(table_name text, vector_column text, k integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.chunk(document_text text, chunk_size integer, chunk_overlap integer, method text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.classify(model text, input_text text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.cluster_kmeans(table_name text, vector_column text, k integer, max_iterations integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.compare(model_ids integer[], test_table text, feature_col text, label_col text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.compute_distribution_divergence(baseline_table text, baseline_vector_col text, current_table text, current_vector_col text, category_column text, category_value text, threshold real) CASCADE;
DROP FUNCTION IF EXISTS neurondb.compute_embedding_quality(table_name text, vector_column text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.create_index(table_name text, vector_col text, index_type text, params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.create_pipeline(pipeline_name text, steps jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.dequantize(quantized_data bytea, method text, dimensions integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.detect_centroid_drift(baseline_table text, baseline_vector_col text, current_table text, current_vector_col text, category_column text, category_value text, threshold real) CASCADE;
DROP FUNCTION IF EXISTS neurondb.detect_outliers_zscore(table_name text, vector_column text, threshold double precision, method text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.detokenize(model text, token_ids integer[]) CASCADE;
DROP FUNCTION IF EXISTS neurondb.detokenize(token_ids integer[]) CASCADE;
DROP FUNCTION IF EXISTS neurondb.discover_topics_simple(table_name text, vector_column text, num_topics integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.distance(vec1 vector, vec2 vector, metric text, p_value double precision) CASCADE;
DROP FUNCTION IF EXISTS neurondb.drop_model(p_model_id integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.drop_model(model_name text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.embed(model text, input_text text, task text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.embed_batch(model text, texts text[], batch_size integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.evaluate(model_id integer, table_name text, feature_col text, label_col text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.export_model(model_id integer, export_format text, export_path text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.export_model_to_onnx(model_id integer, output_path text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.fill_mask(model text, input_text text, params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.get_llm_config() CASCADE;
DROP FUNCTION IF EXISTS neurondb.gpu(operation text, vec1 vector, vec2 vector, params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.health() CASCADE;
DROP FUNCTION IF EXISTS neurondb.hybrid_search_fusion(semantic_table text, lexical_table text, id_column text, semantic_score_column text, lexical_score_column text, semantic_weight real) CASCADE;
DROP FUNCTION IF EXISTS neurondb.import_model_from_onnx(model_id integer, onnx_path text, algorithm text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.list_algorithms() CASCADE;
DROP FUNCTION IF EXISTS neurondb.llm(task text, model text, input_text text, input_array text[], params jsonb, max_length integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.llm_gpu_utilization() CASCADE;
DROP FUNCTION IF EXISTS neurondb.llm_latency_percentile(metric_name text, percentile real) CASCADE;
DROP FUNCTION IF EXISTS neurondb.load(source_type text, source_path text, target_table text, params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.load_dataset(dataset_name text, split text, config text, streaming boolean, cache_dir text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.load_model(project_name text, model_path text, model_format text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.ltr_rerank_pointwise(table_name text, feature_columns text[], weights real[], query_id_column text, query_id_value integer, doc_id_column text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.ltr_score_features(table_name text, feature_columns text[], query_id_column text, query_id_value integer, doc_id_column text, doc_id_value integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.metrics(metric_type text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.mmr_rerank(table_name text, vector_column text, query_vector vector, top_k integer, lambda real) CASCADE;
DROP FUNCTION IF EXISTS neurondb.mmr_rerank_with_scores(table_name text, vector_column text, query_vector vector, top_k integer, lambda real) CASCADE;
DROP FUNCTION IF EXISTS neurondb.model_info(p_model_id integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.models() CASCADE;
DROP FUNCTION IF EXISTS neurondb.monitor_drift_timeseries(table_name text, vector_column text, timestamp_column text, window_interval interval) CASCADE;
DROP FUNCTION IF EXISTS neurondb.predict(model_id integer, features vector) CASCADE;
DROP FUNCTION IF EXISTS neurondb.predict(model_id integer, features real[]) CASCADE;
DROP FUNCTION IF EXISTS neurondb.predict(model_id integer, features double precision[]) CASCADE;
DROP FUNCTION IF EXISTS neurondb.predict(model_name text, features vector) CASCADE;
DROP FUNCTION IF EXISTS neurondb.predict_batch(model_id integer, features_array vector[]) CASCADE;
DROP FUNCTION IF EXISTS neurondb.preprocess(input_vector vector, method text, params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.quantize(input_vector vector, method text, use_gpu boolean) CASCADE;
DROP FUNCTION IF EXISTS neurondb.rag_query(query_text text, document_table text, vector_col text, text_col text, model text, top_k integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.reciprocal_rank_fusion(table_names text[], id_column text, rank_column text, k double precision) CASCADE;
DROP FUNCTION IF EXISTS neurondb.reduce_pca(table_name text, vector_column text, target_dim integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.rerank_ensemble_borda(table_names text[], id_column text, score_column text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.rerank_ensemble_weighted(table_names text[], weights real[], id_column text, score_column text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.search(table_name text, vector_col text, query_vector vector, top_k integer, search_type text, params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.set_llm_config(api_base text, api_key text, default_model text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.similarity(vec1 vector, vec2 vector, metric text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.similarity_histogram(table_name text, vector_column text, num_bins integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.summarize(model text, input_text text, params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.text2text(model text, input_text text, params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.tokenize(model text, input_text text, max_length integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.tokenize(input_text text, max_length integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.train(algorithm text, table_name text, feature_col text, label_col text, params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.train(project_name text, algorithm text, table_name text, label_col text, feature_columns text[], params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.train_pq_codebook(table_name text, vector_column text, num_subspaces integer, num_centroids integer, max_iterations integer) CASCADE;
DROP FUNCTION IF EXISTS neurondb.transform(model text, input_text text, task text) CASCADE;
DROP FUNCTION IF EXISTS neurondb.translate(model text, input_text text, source_lang text, target_lang text, params jsonb) CASCADE;
DROP FUNCTION IF EXISTS neurondb.update_project_timestamp() CASCADE;
DROP FUNCTION IF EXISTS neurondb.version() CASCADE;
DROP FUNCTION IF EXISTS neurondb.zero_shot_classify(model text, input_text text, candidate_labels text[], params jsonb) CASCADE;

DROP TABLE IF EXISTS neurondb.arima_history CASCADE;
DROP TABLE IF EXISTS neurondb.arima_models CASCADE;
DROP TABLE IF EXISTS neurondb.embedding_cache CASCADE;
DROP TABLE IF EXISTS neurondb.embedding_model_config CASCADE;
DROP TABLE IF EXISTS neurondb.feature_stores CASCADE;
DROP TABLE IF EXISTS neurondb.features CASCADE;
DROP TABLE IF EXISTS neurondb.histograms CASCADE;
DROP TABLE IF EXISTS neurondb.hyperparameter_results CASCADE;
DROP TABLE IF EXISTS neurondb.index_maintenance CASCADE;
DROP TABLE IF EXISTS neurondb.index_metadata CASCADE;
DROP TABLE IF EXISTS neurondb.job_queue CASCADE;
DROP TABLE IF EXISTS neurondb.llm_cache CASCADE;
DROP TABLE IF EXISTS neurondb.llm_config CASCADE;
DROP TABLE IF EXISTS neurondb.llm_errors CASCADE;
DROP TABLE IF EXISTS neurondb.llm_jobs CASCADE;
DROP TABLE IF EXISTS neurondb.llm_stats CASCADE;
DROP TABLE IF EXISTS neurondb.ml_experiments CASCADE;
DROP TABLE IF EXISTS neurondb.ml_inference_audit_log CASCADE;
DROP TABLE IF EXISTS neurondb.ml_models CASCADE;
DROP TABLE IF EXISTS neurondb.ml_predictions CASCADE;
DROP TABLE IF EXISTS neurondb.ml_projects CASCADE;
DROP TABLE IF EXISTS neurondb.ml_trained_models CASCADE;
DROP TABLE IF EXISTS neurondb.nb_catalog CASCADE;
DROP TABLE IF EXISTS neurondb.prometheus_metrics CASCADE;
DROP TABLE IF EXISTS neurondb.query_metrics CASCADE;
DROP TABLE IF EXISTS neurondb.rag_operation_audit_log CASCADE;
DROP TABLE IF EXISTS neurondb.rag_pipelines CASCADE;
DROP TABLE IF EXISTS neurondb.rls_policies CASCADE;
DROP TABLE IF EXISTS neurondb.tenant_quotas CASCADE;
DROP TABLE IF EXISTS neurondb.tenant_usage CASCADE;
DROP TABLE IF EXISTS neurondb.text_models CASCADE;

DROP TYPE IF EXISTS neurondb._arima_history CASCADE;
DROP TYPE IF EXISTS neurondb._arima_models CASCADE;
DROP TYPE IF EXISTS neurondb._embedding_cache CASCADE;
DROP TYPE IF EXISTS neurondb._embedding_model_config CASCADE;
DROP TYPE IF EXISTS neurondb._feature_stores CASCADE;
DROP TYPE IF EXISTS neurondb._features CASCADE;
DROP TYPE IF EXISTS neurondb._histograms CASCADE;
DROP TYPE IF EXISTS neurondb._hyperparameter_results CASCADE;
DROP TYPE IF EXISTS neurondb._index_health CASCADE;
DROP TYPE IF EXISTS neurondb._index_maintenance CASCADE;
DROP TYPE IF EXISTS neurondb._index_maintenance_status CASCADE;
DROP TYPE IF EXISTS neurondb._index_metadata CASCADE;
DROP TYPE IF EXISTS neurondb._job_queue CASCADE;
DROP TYPE IF EXISTS neurondb._llm_cache CASCADE;
DROP TYPE IF EXISTS neurondb._llm_config CASCADE;
DROP TYPE IF EXISTS neurondb._llm_error_rates CASCADE;
DROP TYPE IF EXISTS neurondb._llm_errors CASCADE;
DROP TYPE IF EXISTS neurondb._llm_job_status CASCADE;
DROP TYPE IF EXISTS neurondb._llm_jobs CASCADE;
DROP TYPE IF EXISTS neurondb._llm_latency_histograms CASCADE;
DROP TYPE IF EXISTS neurondb._llm_model_stats CASCADE;
DROP TYPE IF EXISTS neurondb._llm_stats CASCADE;
DROP TYPE IF EXISTS neurondb._metrics_summary CASCADE;
DROP TYPE IF EXISTS neurondb._ml_algorithm_type CASCADE;
DROP TYPE IF EXISTS neurondb._ml_deployment_status CASCADE;
DROP TYPE IF EXISTS neurondb._ml_experiments CASCADE;
DROP TYPE IF EXISTS neurondb._ml_inference_audit_log CASCADE;
DROP TYPE IF EXISTS neurondb._ml_model_comparison CASCADE;
DROP TYPE IF EXISTS neurondb._ml_model_status CASCADE;
DROP TYPE IF EXISTS neurondb._ml_model_type CASCADE;
DROP TYPE IF EXISTS neurondb._ml_models CASCADE;
DROP TYPE IF EXISTS neurondb._ml_predictions CASCADE;
DROP TYPE IF EXISTS neurondb._ml_projects CASCADE;
DROP TYPE IF EXISTS neurondb._ml_projects_summary CASCADE;
DROP TYPE IF EXISTS neurondb._ml_trained_models CASCADE;
DROP TYPE IF EXISTS neurondb._nb_catalog CASCADE;
DROP TYPE IF EXISTS neurondb._prometheus_metrics CASCADE;
DROP TYPE IF EXISTS neurondb._query_metrics CASCADE;
DROP TYPE IF EXISTS neurondb._query_performance CASCADE;
DROP TYPE IF EXISTS neurondb._rag_operation_audit_log CASCADE;
DROP TYPE IF EXISTS neurondb._rag_pipelines CASCADE;
DROP TYPE IF EXISTS neurondb._rls_policies CASCADE;
DROP TYPE IF EXISTS neurondb._tenant_quota_usage CASCADE;
DROP TYPE IF EXISTS neurondb._tenant_quotas CASCADE;
DROP TYPE IF EXISTS neurondb._tenant_usage CASCADE;
DROP TYPE IF EXISTS neurondb._text_models CASCADE;
DROP TYPE IF EXISTS neurondb._vector_stats CASCADE;
DROP TYPE IF EXISTS neurondb.arima_history CASCADE;
DROP TYPE IF EXISTS neurondb.arima_models CASCADE;
DROP TYPE IF EXISTS neurondb.embedding_cache CASCADE;
DROP TYPE IF EXISTS neurondb.embedding_model_config CASCADE;
DROP TYPE IF EXISTS neurondb.feature_stores CASCADE;
DROP TYPE IF EXISTS neurondb.features CASCADE;
DROP TYPE IF EXISTS neurondb.histograms CASCADE;
DROP TYPE IF EXISTS neurondb.hyperparameter_results CASCADE;
DROP TYPE IF EXISTS neurondb.index_health CASCADE;
DROP TYPE IF EXISTS neurondb.index_maintenance CASCADE;
DROP TYPE IF EXISTS neurondb.index_maintenance_status CASCADE;
DROP TYPE IF EXISTS neurondb.index_metadata CASCADE;
DROP TYPE IF EXISTS neurondb.job_queue CASCADE;
DROP TYPE IF EXISTS neurondb.llm_cache CASCADE;
DROP TYPE IF EXISTS neurondb.llm_config CASCADE;
DROP TYPE IF EXISTS neurondb.llm_error_rates CASCADE;
DROP TYPE IF EXISTS neurondb.llm_errors CASCADE;
DROP TYPE IF EXISTS neurondb.llm_job_status CASCADE;
DROP TYPE IF EXISTS neurondb.llm_jobs CASCADE;
DROP TYPE IF EXISTS neurondb.llm_latency_histograms CASCADE;
DROP TYPE IF EXISTS neurondb.llm_model_stats CASCADE;
DROP TYPE IF EXISTS neurondb.llm_stats CASCADE;
DROP TYPE IF EXISTS neurondb.metrics_summary CASCADE;
DROP TYPE IF EXISTS neurondb.ml_algorithm_type CASCADE;
DROP TYPE IF EXISTS neurondb.ml_deployment_status CASCADE;
DROP TYPE IF EXISTS neurondb.ml_experiments CASCADE;
DROP TYPE IF EXISTS neurondb.ml_inference_audit_log CASCADE;
DROP TYPE IF EXISTS neurondb.ml_model_comparison CASCADE;
DROP TYPE IF EXISTS neurondb.ml_model_status CASCADE;
DROP TYPE IF EXISTS neurondb.ml_model_type CASCADE;
DROP TYPE IF EXISTS neurondb.ml_models CASCADE;
DROP TYPE IF EXISTS neurondb.ml_predictions CASCADE;
DROP TYPE IF EXISTS neurondb.ml_projects CASCADE;
DROP TYPE IF EXISTS neurondb.ml_projects_summary CASCADE;
DROP TYPE IF EXISTS neurondb.ml_trained_models CASCADE;
DROP TYPE IF EXISTS neurondb.nb_catalog CASCADE;
DROP TYPE IF EXISTS neurondb.prometheus_metrics CASCADE;
DROP TYPE IF EXISTS neurondb.query_metrics CASCADE;
DROP TYPE IF EXISTS neurondb.query_performance CASCADE;
DROP TYPE IF EXISTS neurondb.rag_operation_audit_log CASCADE;
DROP TYPE IF EXISTS neurondb.rag_pipelines CASCADE;
DROP TYPE IF EXISTS neurondb.rls_policies CASCADE;
DROP TYPE IF EXISTS neurondb.tenant_quota_usage CASCADE;
DROP TYPE IF EXISTS neurondb.tenant_quotas CASCADE;
DROP TYPE IF EXISTS neurondb.tenant_usage CASCADE;
DROP TYPE IF EXISTS neurondb.text_models CASCADE;
DROP TYPE IF EXISTS neurondb.vector_stats CASCADE;

DROP FUNCTION IF EXISTS public.array_to_vector(real[]) CASCADE;
DROP FUNCTION IF EXISTS public.array_to_vector(double precision[]) CASCADE;
DROP FUNCTION IF EXISTS public.cluster_dbscan(text, text, double precision, integer) CASCADE;
DROP FUNCTION IF EXISTS public.cluster_gmm(text, text, integer, integer) CASCADE;
DROP FUNCTION IF EXISTS public.cluster_hierarchical(text, text, integer, text) CASCADE;
DROP FUNCTION IF EXISTS public.cluster_kmeans(text, text, integer, integer) CASCADE;
DROP FUNCTION IF EXISTS public.cluster_minibatch_kmeans(text, text, integer, integer, integer) CASCADE;
DROP FUNCTION IF EXISTS public.detect_centroid_drift(text, text, text, text) CASCADE;
DROP FUNCTION IF EXISTS public.detect_outliers_zscore(text, text, double precision, text) CASCADE;
DROP FUNCTION IF EXISTS public.reduce_pca(text, text, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_arima(text, text, text, integer, integer, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_catboost_classifier(text, text, text, integer, double precision, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_catboost_regressor(text, text, text, integer, double precision, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_collaborative_filter(text, text, text, text, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_decision_tree_classifier(table_name text, feature_col text, label_col text, max_depth integer, min_samples_split integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_elastic_net(text, text, text, double precision, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.train_gmm_model_id(table_name text, vector_col text, num_components integer, max_iters integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_kmeans_model_id(table_name text, vector_column text, num_clusters integer, max_iters integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_knn_model_id(table_name text, feature_col text, label_col text, k integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_lasso_regression(text, text, text, double precision, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_lightgbm_classifier(text, text, text, integer, integer, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.train_lightgbm_regressor(text, text, text, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_linear_regression(text, text, text) CASCADE;
DROP FUNCTION IF EXISTS public.train_logistic_regression(text, text, text, integer, double precision, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.train_naive_bayes_classifier(table_name text, feature_col text, label_col text) CASCADE;
DROP FUNCTION IF EXISTS public.train_naive_bayes_classifier_model_id(table_name text, feature_col text, label_col text) CASCADE;
DROP FUNCTION IF EXISTS public.train_opq_rotation(text, text, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_pq_codebook(text, text, integer, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_random_forest_classifier(table_name text, feature_col text, label_col text, n_trees integer, max_depth integer, min_samples_split integer, max_features integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_ridge_regression(text, text, text, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.train_svm_classifier(text, text, text, double precision, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_timeseries_cpu(text, text, text, integer, integer, integer) CASCADE;
DROP FUNCTION IF EXISTS public.train_xgboost_classifier(text, text, text, integer, integer, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.train_xgboost_regressor(text, text, text, integer, integer, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.vector_abs(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_acos(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_add(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_analyze(internal) CASCADE;
DROP FUNCTION IF EXISTS public.vector_append(vector, real) CASCADE;
DROP FUNCTION IF EXISTS public.vector_asin(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_atan(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_avg(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_avg_batch(vector[]) CASCADE;
DROP FUNCTION IF EXISTS public.vector_avg_finalfn(internal) CASCADE;
DROP FUNCTION IF EXISTS public.vector_avg_transfn(internal, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_bray_curtis_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_canberra_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cast_dimension(vector, integer) CASCADE;
DROP FUNCTION IF EXISTS public.vector_chebyshev_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cityblock_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_clip(vector, double precision, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cmp(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_concat(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cos(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosh(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_distance_batch(vector[], vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_distance_fp16(bytea, bytea) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_distance_gpu(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_distance_op(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_greater(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_greater_equal(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_less(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_less_equal(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_sim(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cosine_similarity(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_cross_product(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_dequantize_fp16(bytea) CASCADE;
DROP FUNCTION IF EXISTS public.vector_dequantize_int8(bytea, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_dice_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_dims(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_div(vector, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.vector_divide(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_dot(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_element_sum(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_entropy(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_eq(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_erf(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_erfc(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_exp(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_filter(vector, boolean[]) CASCADE;
DROP FUNCTION IF EXISTS public.vector_ge(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_get(vector, integer) CASCADE;
DROP FUNCTION IF EXISTS public.vector_gt(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_hadamard(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_hamming_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_hash(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_in(cstring) CASCADE;
DROP FUNCTION IF EXISTS public.vector_inner_product(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_inner_product_batch(vector[], vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_inner_product_distance_op(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_inner_product_gpu(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_inner_product_greater(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_inner_product_greater_equal(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_inner_product_less(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_inner_product_less_equal(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_jaccard_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_js_divergence(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_kl_divergence(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_kurtosis(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l1_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_distance_batch(vector[], vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_distance_fp16(bytea, bytea) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_distance_gpu(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_distance_op(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_equal(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_greater(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_greater_equal(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_less(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_less_equal(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_l2_squared_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_le(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_log(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_log10(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_lt(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_mahalanobis_distance(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_matching_coefficient(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_max(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_max(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_mean(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_median(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_min(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_min(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_minkowski_distance(vector, vector, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.vector_minmax_normalize(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_mul(vector, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.vector_ne(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_neg(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_negative_inner_product(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_norm(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_normalize(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_normalize_batch(vector[]) CASCADE;
DROP FUNCTION IF EXISTS public.vector_out(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_pearson_correlation(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_percentile(vector, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.vector_pow(vector, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.vector_prepend(real, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_project(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_quantile(vector, double precision[]) CASCADE;
DROP FUNCTION IF EXISTS public.vector_quantize_binary(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_quantize_fp16(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_quantize_int8(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_recv(internal) CASCADE;
DROP FUNCTION IF EXISTS public.vector_reflect(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_reject(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_rogers_tanimoto_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_rotate(vector, double precision) CASCADE;
DROP FUNCTION IF EXISTS public.vector_russell_rao_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_scale(vector, real[]) CASCADE;
DROP FUNCTION IF EXISTS public.vector_send(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_set(vector, integer, real) CASCADE;
DROP FUNCTION IF EXISTS public.vector_sin(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_sinh(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_skewness(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_slice(vector, integer, integer) CASCADE;
DROP FUNCTION IF EXISTS public.vector_sokal_michener_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_spherical_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_sqrt(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_square(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_squared_l2_distance(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_standardize(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_stddev(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_sub(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_sum(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_sum_batch(vector[]) CASCADE;
DROP FUNCTION IF EXISTS public.vector_sum_finalfn(internal) CASCADE;
DROP FUNCTION IF EXISTS public.vector_sum_transfn(internal, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_tan(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_tanh(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_time_travel(table_name text, vector_col text, timestamp_point timestamp with time zone) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_array_float4(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_array_float8(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_binary(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_binary_gpu(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_bit(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_fp16(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_fp16_gpu(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_halfvec(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_int4(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_int4_gpu(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_int8(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_int8_gpu(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_sparsevec(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_ternary(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_ternary_gpu(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_uint8(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_to_uint8_gpu(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_translate(vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_typmod_in(cstring[]) CASCADE;
DROP FUNCTION IF EXISTS public.vector_typmod_out(integer) CASCADE;
DROP FUNCTION IF EXISTS public.vector_variance(vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_wal_compress(text, text) CASCADE;
DROP FUNCTION IF EXISTS public.vector_wal_decompress(text, text) CASCADE;
DROP FUNCTION IF EXISTS public.vector_wal_estimate_size(text, text) CASCADE;
DROP FUNCTION IF EXISTS public.vector_wal_get_stats() CASCADE;
DROP FUNCTION IF EXISTS public.vector_wal_set_compression(boolean) CASCADE;
DROP FUNCTION IF EXISTS public.vector_weighted_distance(vector, vector, vector) CASCADE;
DROP FUNCTION IF EXISTS public.vector_where(vector, vector, real) CASCADE;
DROP FUNCTION IF EXISTS public.vectorp_in(cstring) CASCADE;
DROP FUNCTION IF EXISTS public.vectorp_out(vectorp) CASCADE;

DROP TYPE IF EXISTS public.binaryvec CASCADE;
DROP TYPE IF EXISTS public.halfvec CASCADE;
DROP TYPE IF EXISTS public.rtext CASCADE;
DROP TYPE IF EXISTS public.sparsevec CASCADE;
DROP TYPE IF EXISTS public.vecmap CASCADE;
DROP TYPE IF EXISTS public.vector CASCADE;
DROP TYPE IF EXISTS public.vectorp CASCADE;
DROP TYPE IF EXISTS public.vgraph CASCADE;

-- Drop any remaining objects that might not be owned by the extension
-- (e.g., objects created manually or in test scenarios)
DROP SCHEMA IF EXISTS neurondb CASCADE;

-- Drop public schema types if they exist (should be dropped by extension, but just in case)
DROP TYPE IF EXISTS public.binaryvec CASCADE;
DROP TYPE IF EXISTS public.halfvec CASCADE;
DROP TYPE IF EXISTS public.rtext CASCADE;
DROP TYPE IF EXISTS public.sparsevec CASCADE;
DROP TYPE IF EXISTS public.vecmap CASCADE;
DROP TYPE IF EXISTS public.vector CASCADE;
DROP TYPE IF EXISTS public.vectorp CASCADE;
DROP TYPE IF EXISTS public.vgraph CASCADE;

\echo '============================================================================'
\echo 'NeurondB Extension Cleanup Complete'
\echo 'All NeurondB objects have been removed.'
\echo '============================================================================'
